[build]
publish = "dist/"
command = "yarn install --production=false && yarn build"

[build.environment]
NODE_ENV = "production"
# TODO: Add staging API url
VUE_APP_API_URL = "http://predict-to-win.herokuapp.com"

[context.production.environment]
# TODO: Add production API url
VUE_APP_API_URL = "http://predict-to-win.herokuapp.com"

# Redirect rule for compatibility with Vue Router
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
